#include "../../mos6502.hpp"

INSTRUCTION(STA, ZERO_PAGE) {
  store<ZERO_PAGE>(AC);
}

INSTRUCTION(STA, ZERO_PAGE_X) {
  store<ZERO_PAGE_X>(AC);
}

INSTRUCTION(STA, ABSOLUTE) {
  store<ABSOLUTE>(AC);
}

INSTRUCTION(STA, ABSOLUTE_X) {
  store<ABSOLUTE_X>(AC);
}

INSTRUCTION(STA, ABSOLUTE_Y) {
  store<ABSOLUTE_Y>(AC);
}

INSTRUCTION(STA, INDIRECT_X) {
  store<INDIRECT_X>(AC);
}

INSTRUCTION(STA, INDIRECT_Y) {
  store<INDIRECT_Y>(AC);
}
