#include "mos6502.hpp"

#define CASE(opcode, instruction, mode) case opcode: instruction<mode>(); break;

void mos6502::execute(std::function<void()> attached) {
  while (true) {
    execute_next();
    if (attached) attached();
  }
}

void mos6502::execute_next() {
  // https://en.wikipedia.org/wiki/MOS_Technology_6502#Instruction_table
  const types::byte opcode = fetch_next();
  switch (opcode) {
    CASE(0x00, BRK, IMPLIED);
    CASE(0x10, BPL, RELATIVE);
    CASE(0x20, JSR, ABSOLUTE);
    CASE(0x30, BMI, RELATIVE);
    CASE(0x40, RTI, IMPLIED);
    CASE(0x50, BVC, RELATIVE);
    CASE(0x60, RTS, IMPLIED);
    CASE(0x70, BVS, RELATIVE);
    CASE(0x90, BCC, RELATIVE);
    CASE(0xA0, LDY, IMMEDIATE);
    CASE(0xB0, BCS, RELATIVE);
    CASE(0xC0, CPY, IMMEDIATE);
    CASE(0xD0, BNE, RELATIVE);
    CASE(0xE0, CPX, IMMEDIATE);
    CASE(0xF0, BEQ, RELATIVE);

    CASE(0x01, ORA, INDIRECT_X);
    CASE(0x11, ORA, INDIRECT_Y);
    CASE(0x21, AND, INDIRECT_X);
    CASE(0x31, AND, INDIRECT_Y);
    CASE(0x41, EOR, INDIRECT_X);
    CASE(0x51, EOR, INDIRECT_Y);
    CASE(0x61, ADC, INDIRECT_X);
    CASE(0x71, ADC, INDIRECT_Y);
    CASE(0x81, STA, INDIRECT_X);
    CASE(0x91, STA, INDIRECT_Y);
    CASE(0xA1, LDA, INDIRECT_X);
    CASE(0xB1, LDA, INDIRECT_Y);
    CASE(0xC1, CMP, INDIRECT_X);
    CASE(0xD1, CMP, INDIRECT_Y);
    CASE(0xE1, SBC, INDIRECT_X);
    CASE(0xF1, SBC, INDIRECT_Y);

    CASE(0xA2, LDX ,IMMEDIATE);

    CASE(0x24, BIT, ZERO_PAGE);
    CASE(0x84, STY, ZERO_PAGE);
    CASE(0x94, STY, ZERO_PAGE_X);
    CASE(0xA4, LDY, ZERO_PAGE);
    CASE(0xB4, LDY, ZERO_PAGE_X);
    CASE(0xC4, CPY, ZERO_PAGE);
    CASE(0xE4, CPX, ZERO_PAGE);

    CASE(0x05, ORA, ZERO_PAGE);
    CASE(0x15, ORA, ZERO_PAGE_X);
    CASE(0x25, AND, ZERO_PAGE);
    CASE(0x35, AND, ZERO_PAGE_X);
    CASE(0x45, EOR, ZERO_PAGE);
    CASE(0x55, EOR, ZERO_PAGE_X);
    CASE(0x65, ADC, ZERO_PAGE);
    CASE(0x75, ADC, ZERO_PAGE_X);
    CASE(0x85, STA, ZERO_PAGE);
    CASE(0x95, STA, ZERO_PAGE_X);
    CASE(0xA5, LDA, ZERO_PAGE);
    CASE(0xB5, LDA, ZERO_PAGE_X);
    CASE(0xC5, CMP, ZERO_PAGE);
    CASE(0xD5, CMP, ZERO_PAGE_X);
    CASE(0xE5, SBC, ZERO_PAGE);
    CASE(0xF5, SBC, ZERO_PAGE_X);

    CASE(0x06, ASL, ZERO_PAGE);
    CASE(0x16, ASL, ZERO_PAGE_X);
    CASE(0x26, ROL, ZERO_PAGE);
    CASE(0x36, ROL, ZERO_PAGE_X);
    CASE(0x46, LSR, ZERO_PAGE);
    CASE(0x56, LSR, ZERO_PAGE_X);
    CASE(0x66, ROR, ZERO_PAGE);
    CASE(0x76, ROR, ZERO_PAGE_X);
    CASE(0x86, STX, ZERO_PAGE);
    CASE(0x96, STX, ZERO_PAGE_Y);
    CASE(0xA6, LDX, ZERO_PAGE);
    CASE(0xB6, LDX, ZERO_PAGE_Y);
    CASE(0xC6, DEC, ZERO_PAGE);
    CASE(0xD6, DEC, ZERO_PAGE_X);
    CASE(0xE6, INC, ZERO_PAGE);
    CASE(0xF6, INC, ZERO_PAGE_X);

    CASE(0x08, PHP, IMPLIED);
    CASE(0x18, CLC, IMPLIED);
    CASE(0x28, PLP, IMPLIED);
    CASE(0x38, SEC, IMPLIED);
    CASE(0x48, PHA, IMPLIED);
    CASE(0x58, CLI, IMPLIED);
    CASE(0x68, PLA, IMPLIED);
    CASE(0x78, SEI, IMPLIED);
    CASE(0x88, DEY, IMPLIED);
    CASE(0x98, TYA, IMPLIED);
    CASE(0xA8, TAY, IMPLIED);
    CASE(0xB8, CLV, IMPLIED);
    CASE(0xC8, INY, IMPLIED);
    CASE(0xD8, CLD, IMPLIED);
    CASE(0xE8, INX, IMPLIED);
    CASE(0xF8, SED, IMPLIED);

    CASE(0x09, ORA, IMMEDIATE);
    CASE(0x19, ORA, ABSOLUTE_Y);
    CASE(0x29, AND, IMMEDIATE);
    CASE(0x39, AND, ABSOLUTE_Y);
    CASE(0x49, EOR, IMMEDIATE);
    CASE(0x59, EOR, ABSOLUTE_Y);
    CASE(0x69, ADC, IMMEDIATE);
    CASE(0x79, ADC, ABSOLUTE_Y);
    CASE(0x99, STA, ABSOLUTE_Y);
    CASE(0xA9, LDA, IMMEDIATE);
    CASE(0xB9, LDA, ABSOLUTE_Y);
    CASE(0xC9, CMP, IMMEDIATE);
    CASE(0xD9, CMP, ABSOLUTE_Y);
    CASE(0xE9, SBC, IMMEDIATE);
    CASE(0xF9, SBC, ABSOLUTE_Y);

    CASE(0x0A, ASL, ACCUMULATOR);
    CASE(0x2A, ROL, ACCUMULATOR);
    CASE(0x4A, LSR, ACCUMULATOR);
    CASE(0x6A, ROR, ACCUMULATOR);
    CASE(0x8A, TXA, IMPLIED);
    CASE(0x9A, TXS, IMPLIED);
    CASE(0xAA, TAX, IMPLIED);
    CASE(0xBA, TSX, IMPLIED);
    CASE(0xCA, DEX, IMPLIED);
    CASE(0xEA, NOP, IMPLIED);

    CASE(0x2C, BIT, ABSOLUTE);
    CASE(0x4C, JMP, ABSOLUTE);
    CASE(0x6C, JMP, INDIRECT);
    CASE(0x8C, STY, ABSOLUTE);
    CASE(0xAC, LDY, ABSOLUTE);
    CASE(0xBC, LDY, ABSOLUTE_X);
    CASE(0xCC, CPY, ABSOLUTE);
    CASE(0xEC, CPX, ABSOLUTE);

    CASE(0x0D, ORA, ABSOLUTE);
    CASE(0x1D, ORA, ABSOLUTE_X);
    CASE(0x2D, AND, ABSOLUTE);
    CASE(0x3D, AND, ABSOLUTE_X);
    CASE(0x4D, EOR, ABSOLUTE);
    CASE(0x5D, EOR, ABSOLUTE_X);
    CASE(0x6D, ADC, ABSOLUTE);
    CASE(0x7D, ADC, ABSOLUTE_X);
    CASE(0x8D, STA, ABSOLUTE);
    CASE(0x9D, STA, ABSOLUTE_X);
    CASE(0xAD, LDA, ABSOLUTE);
    CASE(0xBD, LDA, ABSOLUTE_X);
    CASE(0xCD, CMP, ABSOLUTE);
    CASE(0xDD, CMP, ABSOLUTE_X);
    CASE(0xED, SBC, ABSOLUTE);
    CASE(0xFD, SBC, ABSOLUTE_X);

    CASE(0x0E, ASL, ABSOLUTE);
    CASE(0x1E, ASL, ABSOLUTE_X);
    CASE(0x2E, ROL, ABSOLUTE);
    CASE(0x3E, ROL, ABSOLUTE_X);
    CASE(0x4E, LSR, ABSOLUTE);
    CASE(0x5E, LSR, ABSOLUTE_X);
    CASE(0x6E, ROR, ABSOLUTE);
    CASE(0x7E, ROR, ABSOLUTE_X);
    CASE(0x8E, STX, ABSOLUTE);
    CASE(0xAE, LDX, ABSOLUTE);
    CASE(0xBE, LDX, ABSOLUTE_Y);
    CASE(0xCE, DEC, ABSOLUTE);
    CASE(0xDE, DEC, ABSOLUTE_X);
    CASE(0xEE, INC, ABSOLUTE);
    CASE(0xFE, INC, ABSOLUTE_X);

    default: NOP<IMPLIED>(); break;
  }
}