#include "../types.hpp"
#include "../memory.hpp"
#include <functional>

using processor_status = types::byte;
enum processor_status_flags : processor_status {
  C = (1 << 0),
  Z = (1 << 1),
  I = (1 << 2),
  D = (1 << 3),
  B = (1 << 4),
  U = (1 << 5),
  V = (1 << 6),
  N = (1 << 7)
};

enum addressing_modes {
  IMPLIED,
  IMMEDIATE,
  ACCUMULATOR,
  ZERO_PAGE,
  ZERO_PAGE_X,
  ZERO_PAGE_Y,
  ABSOLUTE,
  ABSOLUTE_X,
  ABSOLUTE_Y,
  INDIRECT,
  INDIRECT_X,
  INDIRECT_Y,
  RELATIVE
};

#define DECLARE(name) template<addressing_modes mode> void name() \
  { static_assert(false, "Unsupported addressing mode"); }
#define INSTRUCTION(name, mode) template<> void mos6502::name<mode>()

struct mos6502 {
  struct cpu_registers {
    types::byte A;
    types::byte X;
    types::byte Y;
    types::byte S;
    types::address PC;
    processor_status P;
  } registers;

  types::byte& A = registers.A;
  types::byte& X = registers.X;
  types::byte& Y = registers.Y;
  types::byte& S = registers.S;
  types::address& PC = registers.PC;
  processor_status& P = registers.P;

  i_memory& m_memory;
  mos6502(i_memory& memory) : m_memory(memory) {}

  constexpr void set_flag(bool condition, processor_status_flags flag) {
    if (condition) P |= flag;
    else P &= ~flag;
  }

  void execute(std::function<void()> attached = nullptr);
  types::byte fetch_next() { return m_memory[PC++]; }
  void execute_next();

  DECLARE(ADC);
  DECLARE(AND);
  DECLARE(ASL);
  DECLARE(BCC);
  DECLARE(BCS);
  DECLARE(BEQ);
  DECLARE(BIT);
  DECLARE(BMI);
  DECLARE(BNE);
  DECLARE(BPL);
  DECLARE(BRK);
  DECLARE(BVC);
  DECLARE(BVS);
  DECLARE(CLC);
  DECLARE(CLD);
  DECLARE(CLI);
  DECLARE(CLV);
  DECLARE(CMP);
  DECLARE(CPX);
  DECLARE(CPY);
  DECLARE(DEC);
  DECLARE(DEX);
  DECLARE(DEY);
  DECLARE(EOR);
  DECLARE(INC);
  DECLARE(INX);
  DECLARE(INY);
  DECLARE(JMP);
  DECLARE(JSR);
  DECLARE(LDA);
  DECLARE(LDX);
  DECLARE(LDY);
  DECLARE(LSR);
  DECLARE(NOP);
  DECLARE(ORA);
  DECLARE(PHA);
  DECLARE(PHP);
  DECLARE(PLA);
  DECLARE(PLP);
  DECLARE(ROL);
  DECLARE(ROR);
  DECLARE(RTI);
  DECLARE(RTS);
  DECLARE(SBC);
  DECLARE(SEC);
  DECLARE(SED);
  DECLARE(SEI);
  DECLARE(STA);
  DECLARE(STX);
  DECLARE(STY);
  DECLARE(TAX);
  DECLARE(TAY);
  DECLARE(TSX);
  DECLARE(TXA);
  DECLARE(TXS);
  DECLARE(TYA);
};

// http://www.6502.org/tutorials/6502opcodes.html#ASL

INSTRUCTION(ADC, IMMEDIATE);
INSTRUCTION(ADC, ZERO_PAGE);
INSTRUCTION(ADC, ZERO_PAGE_X);
INSTRUCTION(ADC, ABSOLUTE);
INSTRUCTION(ADC, ABSOLUTE_X);
INSTRUCTION(ADC, ABSOLUTE_Y);
INSTRUCTION(ADC, INDIRECT_X);
INSTRUCTION(ADC, INDIRECT_Y);

INSTRUCTION(AND, IMMEDIATE);
INSTRUCTION(AND, ZERO_PAGE);
INSTRUCTION(AND, ZERO_PAGE_X);
INSTRUCTION(AND, ABSOLUTE);
INSTRUCTION(AND, ABSOLUTE_X);
INSTRUCTION(AND, ABSOLUTE_Y);
INSTRUCTION(AND, INDIRECT_X);
INSTRUCTION(AND, INDIRECT_Y);

INSTRUCTION(ASL, ACCUMULATOR);
INSTRUCTION(ASL, ZERO_PAGE);
INSTRUCTION(ASL, ZERO_PAGE_X);
INSTRUCTION(ASL, ABSOLUTE);
INSTRUCTION(ASL, ABSOLUTE_X);

INSTRUCTION(BIT, ZERO_PAGE);
INSTRUCTION(BIT, ABSOLUTE);

INSTRUCTION(BPL, RELATIVE);
INSTRUCTION(BMI, RELATIVE);
INSTRUCTION(BVC, RELATIVE);
INSTRUCTION(BVS, RELATIVE);
INSTRUCTION(BCC, RELATIVE);
INSTRUCTION(BCS, RELATIVE);
INSTRUCTION(BNE, RELATIVE);
INSTRUCTION(BEQ, RELATIVE);

INSTRUCTION(BRK, IMPLIED);

INSTRUCTION(CMP, IMMEDIATE);
INSTRUCTION(CMP, ZERO_PAGE);
INSTRUCTION(CMP, ZERO_PAGE_X);
INSTRUCTION(CMP, ABSOLUTE);
INSTRUCTION(CMP, ABSOLUTE_X);
INSTRUCTION(CMP, ABSOLUTE_Y);
INSTRUCTION(CMP, INDIRECT_X);
INSTRUCTION(CMP, INDIRECT_Y);

INSTRUCTION(CPX, IMMEDIATE);
INSTRUCTION(CPX, ZERO_PAGE);
INSTRUCTION(CPX, ABSOLUTE);

INSTRUCTION(CPY, IMMEDIATE);
INSTRUCTION(CPY, ZERO_PAGE);
INSTRUCTION(CPY, ABSOLUTE);

INSTRUCTION(DEC, ZERO_PAGE);
INSTRUCTION(DEC, ZERO_PAGE_X);
INSTRUCTION(DEC, ABSOLUTE);
INSTRUCTION(DEC, ABSOLUTE_X);

INSTRUCTION(EOR, IMMEDIATE);
INSTRUCTION(EOR, ZERO_PAGE);
INSTRUCTION(EOR, ZERO_PAGE_X);
INSTRUCTION(EOR, ABSOLUTE);
INSTRUCTION(EOR, ABSOLUTE_X);
INSTRUCTION(EOR, ABSOLUTE_Y);
INSTRUCTION(EOR, INDIRECT_X);
INSTRUCTION(EOR, INDIRECT_Y);

INSTRUCTION(CLC, IMPLIED);
INSTRUCTION(SEC, IMPLIED);
INSTRUCTION(CLI, IMPLIED);
INSTRUCTION(SEI, IMPLIED);
INSTRUCTION(CLV, IMPLIED);
INSTRUCTION(CLD, IMPLIED);
INSTRUCTION(SED, IMPLIED);

INSTRUCTION(INC, ZERO_PAGE);
INSTRUCTION(INC, ZERO_PAGE_X);
INSTRUCTION(INC, ABSOLUTE);
INSTRUCTION(INC, ABSOLUTE_X);

INSTRUCTION(JMP, ABSOLUTE);
INSTRUCTION(JMP, INDIRECT);

INSTRUCTION(JSR, ABSOLUTE);

INSTRUCTION(LDA, IMMEDIATE);
INSTRUCTION(LDA, ZERO_PAGE);
INSTRUCTION(LDA, ZERO_PAGE_X);
INSTRUCTION(LDA, ABSOLUTE);
INSTRUCTION(LDA, ABSOLUTE_X);
INSTRUCTION(LDA, ABSOLUTE_Y);
INSTRUCTION(LDA, INDIRECT_X);
INSTRUCTION(LDA, INDIRECT_Y);

INSTRUCTION(LDX, IMMEDIATE);
INSTRUCTION(LDX, ZERO_PAGE);
INSTRUCTION(LDX, ZERO_PAGE_Y);
INSTRUCTION(LDX, ABSOLUTE);
INSTRUCTION(LDX, ABSOLUTE_Y);

INSTRUCTION(LDY, IMMEDIATE);
INSTRUCTION(LDY, ZERO_PAGE);
INSTRUCTION(LDY, ZERO_PAGE_X);
INSTRUCTION(LDY, ABSOLUTE);
INSTRUCTION(LDY, ABSOLUTE_X);

INSTRUCTION(LSR, ACCUMULATOR);
INSTRUCTION(LSR, ZERO_PAGE);
INSTRUCTION(LSR, ZERO_PAGE_X);
INSTRUCTION(LSR, ABSOLUTE);
INSTRUCTION(LSR, ABSOLUTE_X);

INSTRUCTION(NOP, IMPLIED);

INSTRUCTION(ORA, IMMEDIATE);
INSTRUCTION(ORA, ZERO_PAGE);
INSTRUCTION(ORA, ZERO_PAGE_X);
INSTRUCTION(ORA, ABSOLUTE);
INSTRUCTION(ORA, ABSOLUTE_X);
INSTRUCTION(ORA, ABSOLUTE_Y);
INSTRUCTION(ORA, INDIRECT_X);
INSTRUCTION(ORA, INDIRECT_Y);

INSTRUCTION(TAX, IMPLIED);
INSTRUCTION(TXA, IMPLIED);
INSTRUCTION(DEX, IMPLIED);
INSTRUCTION(INX, IMPLIED);
INSTRUCTION(TAY, IMPLIED);
INSTRUCTION(TYA, IMPLIED);
INSTRUCTION(DEY, IMPLIED);
INSTRUCTION(INY, IMPLIED);

INSTRUCTION(ROL, ACCUMULATOR);
INSTRUCTION(ROL, ZERO_PAGE);
INSTRUCTION(ROL, ZERO_PAGE_X);
INSTRUCTION(ROL, ABSOLUTE);
INSTRUCTION(ROL, ABSOLUTE_X);

INSTRUCTION(ROR, ACCUMULATOR);
INSTRUCTION(ROR, ZERO_PAGE);
INSTRUCTION(ROR, ZERO_PAGE_X);
INSTRUCTION(ROR, ABSOLUTE);
INSTRUCTION(ROR, ABSOLUTE_X);

INSTRUCTION(RTI, IMPLIED);

INSTRUCTION(RTS, IMPLIED);

INSTRUCTION(SBC, IMMEDIATE);
INSTRUCTION(SBC, ZERO_PAGE);
INSTRUCTION(SBC, ZERO_PAGE_X);
INSTRUCTION(SBC, ABSOLUTE);
INSTRUCTION(SBC, ABSOLUTE_X);
INSTRUCTION(SBC, ABSOLUTE_Y);
INSTRUCTION(SBC, INDIRECT_X);
INSTRUCTION(SBC, INDIRECT_Y);

INSTRUCTION(STA, ZERO_PAGE);
INSTRUCTION(STA, ZERO_PAGE_X);
INSTRUCTION(STA, ABSOLUTE);
INSTRUCTION(STA, ABSOLUTE_X);
INSTRUCTION(STA, ABSOLUTE_Y);
INSTRUCTION(STA, INDIRECT_X);
INSTRUCTION(STA, INDIRECT_Y);
INSTRUCTION(TXS, IMPLIED);
INSTRUCTION(TSX, IMPLIED);
INSTRUCTION(PHA, IMPLIED);
INSTRUCTION(PLA, IMPLIED);
INSTRUCTION(PHP, IMPLIED);
INSTRUCTION(PLP, IMPLIED);

INSTRUCTION(STX, ZERO_PAGE);
INSTRUCTION(STX, ZERO_PAGE_Y);
INSTRUCTION(STX, ABSOLUTE);

INSTRUCTION(STY, ZERO_PAGE);
INSTRUCTION(STY, ZERO_PAGE_X);
INSTRUCTION(STY, ABSOLUTE);
